[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "dist"
  command = "npx pnpm@6 i --store=node_modules/.pnpm-store && npx pnpm@6 run build:ci"