[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "./apps/portfolio/dist"
  command = "npx pnpm@v6 i --store=node_modules/.pnpm-store --shamefully-hoist && npx pnpm@v6 run build:ci"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200