name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install --no-frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm run build:portfolio
          start: pnpm run start:portfolio
          wait-on: http://localhost:3000
