name: e2e
on: [push]

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  cypress-run:
    name: E2E on Chrome
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install --no-frozen-lockfile --shamefully-hoist

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: pnpm build:ui && pnpm run build:portfolio
          start: pnpm run start:portfolio
          wait-on: http://localhost:3000
